// --------------Atama Operatorleri---------
/*

  = (atama operatoru)
  ==  (esittir anlamına gelir)
  === (hem tipleri hemde değerlerinin esit olup olmadıgına bakar)
  += (direk toplar)
  *= (direk carpar)
  /= (birek boler)
  %= (direk modunu oalır)
  **= (direk karesini alır)

*/

console.log(5===5);//true
console.log(5==="5")//false
console.log("5"==="5")//true
console.log(5=="5")//true cunku == de veri tipine bakmaz  sadece icindeki deger aynimi ona bakar




//! ------------- */-/+= -----------

let sayi = 4;
sayi = sayi + 2;
console.log(sayi);  
                     //TODO: uzatmadan sayiyi eklememize yardimci olur
let number = 7;
number += 2;
console.log(number)

//!------------------------------







