/*
!-----Veri Tipleri-----!

1-String
2-Number
3-Boolean (true false' dan olusur)
4-Null (bos anlamina gelir)
5-Undefined(tanimlanmamis veri tipi)
6-Object
7-Function


*/


let isim = "Firat"; //String veri tipi

let sayi1 = 21; //Number veri tipi

console.log(5>2); //Boolean veri tipi

let c = null;

let a;// Undefined veri tipi herhangi bir değer atamasi yapilmamis

let human = { //TODO Object veri tipi
    name: "Firat",
    surname: "A.",
    year: 21
}

let func = function() {
    console.log("Hi!"); // function veri tipi
}







