//!  ARİTMETİK OPERATÖRLER

/*================> = atama operatörü önemli!

+ (toplama operatörü)
- (çıkarma operatörü)
* (çarpma operatörü)
/ (bölme operatörü)
% (mod alma operatörüdür, bir sayiyi bir sayiya böldüğünde kalanı vermesi için kullanılır)
++ (sayiyi 1 arttırır)
-- (sayiyi 1 azaltır)
** (sayinin üssünü almak icin kullanilir)

//? degiskenler ıkı kalıptan olusuyorsa 2. kalıp buyuk harfle baslar siraNo gibi

*/

let a = 5; //= -> atama operatörüdür 5 değerini a ya atar
let isim = "Firat"

console.log(5+7); // (toplama ıslemı yapar)


let sayi1 = "5";
let sayi2 = 2;

console.log(sayi1+sayi2); //sayı biri string olarak algılar ve 52 olarak yazar

let o = 10;
o++;//11
o++;//12
o--;//11
console.log(o);

console.log(4**2);//(4**2) -> 4^2=16
