//--------Mantıksal Operatorler---------

/*
    &&: ve
    ||: veya
    !: degil

*/

let yas = 20;
let para = 3500;
let saglikliMi = false;

console.log(yas>18 && para > 1500 && saglikliMi == true); //TODO: Ve baglacinda butun durumların true olmasi gerekir yoksa kosul direk false doner.


console.log(yas>15 || para>1500 || saglikliMi ==false ); //TODO: Veya baglacinda bir durum dogru ise true doner.


                //t
console.log(  !(5>3)  );//TODO: unlem oldugu icin dogru durumun degili false olarak yazar

