// ----------Else İf--------
/*
if(kosul) {
?    kodlar
}else if(kosul) {
?   kodlar
}else if(kosul) {
?    kodlar
}else {
?    kodlar
}
*/
// 1.yol 2.yol 3.yol
let secilenYol = prompt("1.yol 2.yol 3.yol <|&|> Gitmek istediğiniz yolu seçiniz: ");


if(secilenYol==="1") {
    console.log("1.yol seçildi! ");
}else if(secilenYol==="2") {
    console.log("2.yol seçildi! ");
}else if(secilenYol==="3") {
    console.log("3.yol seçildi! ");
}else {
    console.log("Lütfen belirlenen yollardan birini seçiniz! ");
}
