//!1.yontem
//Document write ile cikti verme
//?document.write("Hello World! <br>")  // br bir sonraki ifadeyi alt satıra yazar
//?document.write("I am Firat")
//?document.write(true)



//!2.yontem
//consolelog ile cikti verme
//?console.log("Hello World!");
//?console.log("Firat");
//?console.clear();  //*konsolu temizler




//!3.yontem
//Alert(uyari)

//?alert("Wrong!");

console.log(windows);


